### ISSUE TITLE
please deploy https

### ISSUE THREAD

**Issue by focusaurus** [nodejs/nodejs.org-archive#38]
plaintext HTTP plus checksums in the HTML page don't provide protection for the node.js binary distributions from tampering. Examples of other similar projects that provide https:

https://www.python.org/
https://www.ruby-lang.org/en/
https://golang.org/

**Comment by jclulow** [comment]
While your assertion is true, it is also true that transport encryption (e.g. HTTPS) alone doesn't really protect against tampering either.

What _does_ protect against tampering is cryptographic signatures of the binaries or a manifest of checksums.  After joyent/node-website#21, the checksum link on the download page is actually to a signed copy of the `SHASUMS.txt` file, e.g. http://nodejs.org/dist/v0.10.31/SHASUMS.txt.asc.  If you verify this signature, you can be sure the checksums have not been tampered with.  You can then verify the integrity of your downloaded binary against this verified checksum manifest, e.g. using the `keybase` tool...

```
$ curl -sSfkOL http://nodejs.org/dist/v0.10.31/SHASUMS.txt.asc
$ curl -sSfkOL http://nodejs.org/dist/v0.10.31/node-v0.10.31-sunos-x86.tar.gz
$ ls
node-v0.10.31-sunos-x86.tar.gz  SHASUMS.txt.asc
$ keybase verify SHASUMS.txt.asc
info: Valid signature from keybase user tjfontaine (tracking remotely & locally)
info: Signed about 21 hours ago (Tue Aug 19 2014 15:12:01 GMT-0700 (PST))
✔ public key fingerprint: 7937 DFD2 AB06 298B 2293 C318 7D33 FF9D 0246 406D
✔ "tjfontaine" on github: https://gist.github.com/9512993

$ shasum node-v0.10.31-sunos-x86.tar.gz
d854aea39eba1d567f4a8d09cfdadba9bc4c55cb  node-v0.10.31-sunos-x86.tar.gz
$ grep d854aea39eba1d567f4a8d09cfdadba9bc4c55cb SHASUMS.txt.asc
d854aea39eba1d567f4a8d09cfdadba9bc4c55cb  node-v0.10.31-sunos-x86.tar.gz
```

**Comment by focusaurus** [comment]
Thanks for those instructions! Very nice. I think https is still worthwhile even if just to give folks warm fuzzies.

**Comment by zhanzhenzhen** [comment]
+1 for deploying https.

Considering npmjs.org is using https for both the website and the `npm` command, why its underlying "node" can only be downloaded using http? That's very unreasonable.

Yes, we can still validate the author tjfontaine by using PGP, but:
1. PGP tool is not built-in in both Mac and Windows.
2. Many people don't know where to find tjfontaine's public key.

Two recommendations:
1. Let nodejs.org run completely on HTTPS. But maybe this is expensive. So there's option 2:
2. In your download page, add a link to a gist that contains the checksums of the files. The gist must be under Joyent or one of the main contributors' namespace. Because github.com is HTTPS protected, this also makes sense.

> transport encryption (e.g. HTTPS) alone doesn't really protect against tampering either

This is only for self-signed certificates. As long as the certificate is signed by a well known CA, and the website itself is trusted, I think it can protect against tampering.

**Comment by tjfontaine** [comment]
I cannot stress this enough, it is not sufficient to download a tarball via HTTPS to ensure the integrity of the tarball. All you are verifying by downloading the tarball over HTTPS is that these sets of bytes were successfully downloaded without someone in the middle mutating them.

Downloading files over HTTPS does not in **any** **way** insure that the files on the remote server are indeed what they claim to be.

The **_only**_ way to verify the integrity of the tarball's contents is to use the checksum provided in the `SHASUM.txt` or `SHASUM256.txt` files, and the only way to verify the contents of those are unmolested is to use gpg and verify the signature from `SHASUM.txt.asc` and `SHASUM256.txt.asc`.

To verify the signature you need to use 3rd party sites, for instance: https://keybase.io/tjfontaine which also has me post to multiple locations such that others can verify my identity. [see also npm install -g keybase]

And even then you have to be mindful to know if the key has been revoked.

---

To reiterate, it is not sufficient to download a tarball over HTTPS to guarantee the contents of the tarball are indeed what you think they are. HTTPS **_only**_ ensures that the **transport** of those **bytes** happen in an unmolested fashion.

---

That being said I am getting certificates for nodejs.org, but please do not let that give you a false sense of security about what it is exactly that you're downloading, if you want that you must use one of the ways previously described.

**Comment by zhanzhenzhen** [comment]
Ha, yes, the only way to insure the integrity of the tarball's contents is to use Microsoft Authenticode on Windows, or other tools like PGP on other platforms.

But, "nodejs.org" is the official website, it's unlikely that it will tamper with the tarball files. If we rely on PGP then we trust you, @tjfontaine. If we rely on SSL then we trust nodejs.org. I think either makes sense.

**Comment by misterdjules** [comment]
Fixed by https://github.com/nodejs/nodejs.org/pull/127.

Please be mindful that it only guarantees you that the content you download is sent from nodejs.org, and that the bytes were not tampered with in transit. It does not guarantee you that the content hasn't been tampered with before or after. For that, you'll need to verify the digital signatures provided with each releases.
